feat: create register
Grupo3G-Drivent-CCJKT/drivent-backend pull request #14
Opened 2023-05-26 22:53 UTC by carlmnm

2023-05-27 11:17 UTC, thi-coutinho requested changes

2023-05-27 11:17 UTC, thi-coutinho commented on src/repositories/activities-repository/index.ts
> +      id: userId,
Aqui ele ta comparando o id do registro com o userID, deveia ser o userID com o UserId

2023-05-29 02:18 UTC, kendy-karakawa approved these changes

2023-05-29 12:06 UTC, thi-coutinho approved these changes

2023-05-29 12:06 UTC, merged